version: 2

project_name: funlang

before:
  hooks:
    - go mod tidy

builds:
  # Linux и Windows
  - id: build-linux-win
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: fun
    flags:
      - -trimpath
    ldflags:
      - -s -w
    hooks:
      post:
        - upx --best --lzma "{{ .Path }}"

  # macOS
  - id: build-darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: fun
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'ci:'